apiVersion: v2
name: telegram-connector
description: Helm chart for deploying the Telegram Connector service.
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/agynio/telegram-connector
sources:
  - https://github.com/agynio/telegram-connector
dependencies:
  - name: service-base
    version: ">=0.1.4 <1.0.0"
    repository: oci://ghcr.io/agynio/charts
